### ISSUE TITLE
causing vs 2019 to crash! (see callstack)

### ISSUE THREAD

**Issue by rimatsky** [kaby76/AntlrVSIX#22]
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at System.Convert.ToUInt32(Int32)
   at System.Int32.System.IConvertible.ToUInt32(System.IFormatProvider)
   at System.Convert.ToUInt32(System.Object)
   at Workspaces.Loader.ProcessHierarchyNodeRecursively(Workspaces.Container, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32)
   at Workspaces.Loader.ProcessHierarchyNodeRecursively(Workspaces.Container, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32)
   at Workspaces.Loader.ProcessHierarchyNodeRecursively(Workspaces.Container, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32)
   at Workspaces.Loader+<LoadAsync>d__6.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at **AntlrVSIX**.File.ViewCreationListener+<VsTextViewCreated>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by kaby76** [comment]
Looks like you're opening a file, and then it crashes in the code that reads projects/solutions. This code is based on something I got from MS. It is a tree walker of IVsHierarchy COM objects, completely not understandable, and it looks like it's not very robust either. As I no longer need to grab the project/solution hierarchy using this IVsHierarchy tree walker, and since it's hardly portable to an LSP server outside of Visual Studio, I'll replace this code first with the previous more robust EnvDTE.Project/ProjectItem tree walker to read the project/solution layout. It will be a couple of days to fix because I'm in the middle of extending the symbol table scoping classes to better handle other programming languages. In the meanwhile, turn off the extension. If you are building an Antlr-parser program, you should still be able to do that since that is completely independent.

**Comment by rimatsky** [comment]
10x! @kaby76 
BTW, great tool, great blog (http://codinggorilla.com/)... and as as consumer of your extension, thank you your work FOSS (:
